# WATAG — built by Sidedoor Digital
# Intellectual property of Sidedoor Digital

name = "watag"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-23"

[[d1_databases]]
binding = "WATAG_DB"
database_name = "watag-db"
database_id = "a055f1cf-2ea9-4327-9ed9-881522a3c38d"
